# **Machine Learning –: Train & Test Datasets**
-----
-----

## Creating array

In [1]:
import numpy as np

In [3]:
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## train_test_split(p) function

In [4]:
from sklearn.model_selection import train_test_split

In [7]:
dataset = np.arange(10) 
 
result = train_test_split(dataset) 
 
print(dataset) 
print()
print(result)


[0 1 2 3 4 5 6 7 8 9]

[array([9, 3, 5, 4, 2, 0, 7]), array([1, 8, 6])]


## Creating an array and splitting

In [9]:
dataset = np.arange(10) 
 
X_train,X_test = train_test_split(dataset) 
 
print(dataset) 
print()
print(X_train)
print(X_test)


[0 1 2 3 4 5 6 7 8 9]

[4 8 5 9 1 0 6]
[3 7 2]


## Given test size

In [13]:
X_train,X_test = train_test_split(dataset,test_size = 4)

print(dataset)
print()
print(X_train)
print(X_test)


[0 1 2 3 4 5 6 7 8 9]

[4 0 9 1 6 7]
[5 8 3 2]


## Given train size

In [14]:
X_train,X_test = train_test_split(dataset,train_size = 6)

print(dataset)
print()
print(X_train)
print(X_test)


[0 1 2 3 4 5 6 7 8 9]

[1 9 4 3 8 2]
[7 6 5 0]


### Percentage wise given train_size & test_size 

In [15]:
X_train,X_test = train_test_split(dataset, train_size = 0.6, test_size = 0.4)

print(dataset)
print()
print(X_train)
print(X_test)


[0 1 2 3 4 5 6 7 8 9]

[9 5 8 7 4 2]
[0 3 1 6]


### ***Creating an array an Splitting***

In [17]:
dataset = np.arange(20)

print(dataset)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [18]:

result = train_test_split(dataset)
result


[array([19, 12,  0,  8,  4,  3, 11, 14, 16, 17,  6, 18,  2,  5,  9]),
 array([10, 13,  1,  7, 15])]

### Using reshape() method

In [21]:
dataset = np.arange(20).reshape(2,10)

In [22]:
dataset

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

### Using T attributes

In [24]:
dataset = np.arange(20).reshape(2,10).T

dataset

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

### Splitting and  train & test dataset

In [27]:
X_train,X_test = train_test_split(dataset)

print(X_train)
print()
print(X_test)

[[ 1 11]
 [ 0 10]
 [ 7 17]
 [ 5 15]
 [ 8 18]
 [ 2 12]
 [ 4 14]]

[[ 9 19]
 [ 6 16]
 [ 3 13]]


In [31]:
X = np.arange(20).reshape(2, 10).T 
 
y = np.arange(10) 
 
X_train, X_test, y_train, y_test = train_test_split(X, y) 
 
print(X_train) 
print() 
print(X_test) 
print() 

print(y_train) 
print() 
print(y_test) 


[[ 2 12]
 [ 5 15]
 [ 9 19]
 [ 6 16]
 [ 4 14]
 [ 1 11]
 [ 8 18]]

[[ 7 17]
 [ 0 10]
 [ 3 13]]

[2 5 9 6 4 1 8]

[7 0 3]


## Using **( random_state = 0 )** keyword arguments that is purpose of no suffeling

In [33]:
X = np.arange(20).reshape(2, 10).T 
 
y = np.arange(10) 
 
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0) 
 
print(X_train) 
print() 
print(X_test) 
print() 

print(y_train) 
print() 
print(y_test) 


[[ 9 19]
 [ 1 11]
 [ 6 16]
 [ 7 17]
 [ 3 13]
 [ 0 10]
 [ 5 15]]

[[ 2 12]
 [ 8 18]
 [ 4 14]]

[9 1 6 7 3 0 5]

[2 8 4]
