# **Machine Learning -: K Nearest Neighbor**
------
-------

### Import required Libraries

In [1]:
import pandas as pd
import numpy as np


### Loading the Dataset

In [2]:
from sklearn.datasets import load_iris


In [3]:
iris = load_iris()

In [4]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

### Displaying **Data**

In [5]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

### Displaying **feature_names**

In [6]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

### Displaying **target** value

In [7]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Displaying **target_names**

In [8]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

### Creating DataFrame Using iris dataset

In [9]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)

df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

### Adding **target** column & Assign with values

In [10]:
df['target'] = iris.target

df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   target  
0       0  
1       0  
2       0

- ### Displaying **target == 0** flowers

In [11]:
df[df.target == 0].head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [12]:
len(df[df.target == 0])

50

- ### Displaying **target == 1** flowers

In [13]:
df[df.target == 1].head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

    target  
50       1  
51       1  
52       1  
53       1  
54       1

In [14]:
len(df[df.target == 1])

50

- ### Displaying **target == 2** flowers

In [15]:
df[df.target == 2].head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
100                6.3               3.3                6.0               2.5   
101                5.8               2.7                5.1               1.9   
102                7.1               3.0                5.9               2.1   
103                6.3               2.9                5.6               1.8   
104                6.5               3.0                5.8               2.2   

     target  
100       2  
101       2  
102       2  
103       2  
104       2

In [16]:
len(df[df.target == 2])

50

### Adding **flower** column & assign with value

In [17]:
df['flower_name'] = df.target.apply(lambda x: iris.target_names[x]) 

df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target flower_name  
0       0      setosa  
1       0      setosa  
2       0      setosa  
3       0      setosa  
4       0      setosa

- ### Displaying All **setosa** flowers

In [18]:
setosa_50 = df[:50]

setosa_50.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target flower_name  
0       0      setosa  
1       0      setosa  
2       0      setosa  
3       0      setosa  
4       0      setosa

In [19]:
len(setosa_50)

50

- ### Displaying All **versicolor** flowers

In [20]:
versicolor_50 = df[50 : 100]

versicolor_50.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

    target flower_name  
50       1  versicolor  
51       1  versicolor  
52       1  versicolor  
53       1  versicolor  
54       1  versicolor

In [21]:
len(versicolor_50)

50

- ### Displaying All **virginica** flowers

In [22]:
virginica_50 = df[100 : ]

virginica_50.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
100                6.3               3.3                6.0               2.5   
101                5.8               2.7                5.1               1.9   
102                7.1               3.0                5.9               2.1   
103                6.3               2.9                5.6               1.8   
104                6.5               3.0                5.8               2.2   

     target flower_name  
100       2   virginica  
101       2   virginica  
102       2   virginica  
103       2   virginica  
104       2   virginica

In [23]:
len(virginica_50)

50

## Data Preparation

In [24]:
X = df.drop(['target','flower_name'], axis = 'columns')

y = df.target

In [25]:
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [26]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int32

## Splitting the Dataset

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X.values, y, test_size=0.2)


### Model Creation with  **KNeighborsclassifier**

In [29]:
from sklearn.neighbors import KNeighborsClassifier 


In [30]:
knn = KNeighborsClassifier(n_neighbors = 5)


### Model Training

In [31]:
knn.fit(X_train, y_train) 

X_train


array([[4.9, 3.1, 1.5, 0.1],
       [5.9, 3.2, 4.8, 1.8],
       [4.8, 3. , 1.4, 0.1],
       [5.8, 2.6, 4. , 1.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.1, 3.8, 1.9, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [7.9, 3.8, 6.4, 2. ],
       [4.7, 3.2, 1.6, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [6.1, 2.8, 4.7, 1.2],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.9, 5.6, 1.8],
       [5.7, 3. , 4.2, 1.2],
       [6.3, 2.3, 4.4, 1.3],
       [5.1, 3.5, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 3.5, 1.4, 0.3],
       [6.3, 3.4, 5.6, 2.4],
       [5. , 3.2, 1.2, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [5.5, 4.2, 1.4, 0.2],
       [5.6, 2.8, 4.9, 2. ],
       [5. , 3.4, 1.6, 0.4],
       [7.4, 2.8, 6.1, 1.9],
       [6. , 2.2, 4. , 1. ],
       [5.7, 2.9, 4.2, 1.3],
       [6.4, 3.2, 4.5, 1.5],
       [5.4, 3.4, 1.7, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [5.4, 3. , 4.5, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [5.7, 2.6, 3.5, 1. ],
       [5.8, 2

In [32]:
y_train

9      0
70     1
12     0
92     1
31     0
      ..
65     1
149    2
86     1
146    2
11     0
Name: target, Length: 120, dtype: int32

### Check the Score

In [33]:
knn.score(X_test, y_test)

0.9333333333333333

### Model Prediction

In [34]:
knn.predict([[6.7, 3.1, 4.7, 1.5]])

array([1])

In [35]:
knn.predict([[4.6,3.1,1.5,0.2]])

array([0])

In [36]:
y_pred = knn.predict(X_test)

In [37]:
y_pred

array([1, 0, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 2, 1, 1, 1,
       2, 2, 2, 0, 1, 2, 0, 2])

## Model evaluation 

In [38]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix 


In [39]:
confusion_matrix(y_test, y_pred)

array([[ 9,  0,  0],
       [ 0,  8,  2],
       [ 0,  0, 11]], dtype=int64)

In [40]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.80      1.00      0.89         8
           2       1.00      0.85      0.92        13

    accuracy                           0.93        30
   macro avg       0.93      0.95      0.94        30
weighted avg       0.95      0.93      0.93        30

