# **Machine Learning -: Naive Bayes Classifier**
-----
------

### Import the Libraries

In [1]:
import pandas as pd
import numpy as np


### Loading the Dataset

In [2]:
df = pd.read_csv("E:\\Data Science Notes\\8.MACHINE LEARNING\\titanic.csv") 

df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [3]:
df.shape

(891, 12)

In [4]:
df.describe()

PassengerId      Pclass         Age       SibSp       Parch  \
count   891.000000  891.000000  714.000000  891.000000  891.000000   
mean    446.000000    2.308642   29.699118    0.523008    0.381594   
std     257.353842    0.836071   14.526497    1.102743    0.806057   
min       1.000000    1.000000    0.420000    0.000000    0.000000   
25%     223.500000    2.000000   20.125000    0.000000    0.000000   
50%     446.000000    3.000000   28.000000    0.000000    0.000000   
75%     668.500000    3.000000   38.000000    1.000000    0.000000   
max     891.000000    3.000000   80.000000    8.000000    6.000000   

             Fare    Survived  
count  891.000000  891.000000  
mean    32.204208    0.383838  
std     49.693429    0.486592  
min      0.000000    0.000000  
25%      7.910400    0.000000  
50%     14.454200    0.000000  
75%     31.000000    1.000000  
max    512.329200    1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Name         891 non-null    object 
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object 
 10  Embarked     889 non-null    object 
 11  Survived     891 non-null    int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [6]:
df.isnull().sum()

PassengerId      0
Name             0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Survived         0
dtype: int64

### Accessing only Uses Columns

In [7]:
df = pd.read_csv("E:\\Data Science Notes\\8.MACHINE LEARNING\\titanic.csv", usecols = ['Pclass', 'Sex', 'Age', 'Fare', 'Survived']) 

df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

### Data Preparation

In [8]:
X = df.drop('Survived',axis = 1)

y = df.Survived

In [9]:
X.head()

Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [10]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

### Creating dummy Variables

In [11]:
dummies = pd.get_dummies(X.Sex, dtype = int) 

In [12]:
dummies.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

### Concatenating the dataframe with dummies Variables

In [13]:
X = pd.concat([X, dummies], axis = 'columns') 


In [14]:
X.head()

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

### Dropping unnecessary column

In [15]:
X.drop(['Sex', 'male'], axis = 'columns', inplace = True)

In [16]:
X.head(3)

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1

### Find Missing Values 

In [17]:
X.isnull().sum()

Pclass      0
Age       177
Fare        0
female      0
dtype: int64

### Fill missing values in **Age** column with mean 

In [18]:
X.Age = X.Age.fillna(X.Age.mean()) 

In [19]:
X.isnull().sum()

Pclass    0
Age       0
Fare      0
female    0
dtype: int64

### Splitting the Dataset

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X.values, y, test_size=0.3)


In [22]:
X_train[:5,:]

array([[ 1.    , 19.    , 26.2833,  1.    ],
       [ 1.    , 35.    , 26.55  ,  0.    ],
       [ 3.    , 14.5   , 14.4542,  1.    ],
       [ 2.    , 24.    , 27.    ,  1.    ],
       [ 1.    , 62.    , 80.    ,  1.    ]])

### Model Creation

In [23]:
from sklearn.naive_bayes import GaussianNB

In [24]:
model = GaussianNB() 


### Model training

In [25]:
model.fit(X_train, y_train) 

GaussianNB()

### Prediction

In [26]:
X_test[0:5]

array([[ 1.    , 30.    , 27.75  ,  0.    ],
       [ 3.    , 45.    ,  6.975 ,  0.    ],
       [ 2.    , 30.    , 13.    ,  0.    ],
       [ 3.    , 19.    ,  7.8542,  1.    ],
       [ 3.    , 26.    ,  7.8542,  0.    ]])

In [27]:
model.predict(X_test[0:5])

array([0, 0, 0, 1, 0], dtype=int64)

### Prediction probability

In [28]:
model.predict_proba(X_test[:5])


array([[0.81046087, 0.18953913],
       [0.96476693, 0.03523307],
       [0.93322428, 0.06677572],
       [0.38217014, 0.61782986],
       [0.96362915, 0.03637085]])

In [29]:
model.predict_proba(X_test[:10])


array([[8.10460865e-01, 1.89539135e-01],
       [9.64766926e-01, 3.52330736e-02],
       [9.33224276e-01, 6.67757237e-02],
       [3.82170142e-01, 6.17829858e-01],
       [9.63629148e-01, 3.63708523e-02],
       [2.14514362e-02, 9.78548564e-01],
       [9.25243759e-01, 7.47562412e-02],
       [3.53960161e-13, 1.00000000e+00],
       [9.67295111e-01, 3.27048888e-02],
       [9.65896527e-01, 3.41034729e-02]])

### Find : Cross validation score

In [30]:
from sklearn.model_selection import cross_val_score 

In [31]:
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.768     , 0.792     , 0.808     , 0.77419355, 0.75      ])

In [32]:
cross_val_score(GaussianNB(),X_train, y_train, cv=10)

array([0.79365079, 0.73015873, 0.76190476, 0.80645161, 0.80645161,
       0.80645161, 0.75806452, 0.79032258, 0.74193548, 0.74193548])